var Module=(()=>function(aa={}){function ba(){var a=M.buffer;g.HEAP8=y=new Int8Array(a);g.HEAP16=S=new Int16Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=r=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=ca=new Float32Array(a);g.HEAPF64=da=new Float64Array(a);g.HEAP64=N=new BigInt64Array(a);g.HEAPU64=new BigUint64Array(a)}function E(a){a="Aborted("+a+")";F(a);ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");
T(a);throw a;}function fa(a){if(a==B&&O)return new Uint8Array(O);if(U)return U(a);throw"both async and sync fetching of the wasm failed";}function ya(a){return O||!ha&&!P||"function"!=typeof fetch?Promise.resolve().then(()=>fa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>fa(a))}function ia(a,b,d){return ya(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(d,e=>{F(`failed to asynchronously prepare wasm: ${e}`);
E(e)})}function za(a,b,d,e){return a||"function"!=typeof WebAssembly.instantiateStreaming||b.startsWith("data:application/octet-stream;base64,")||"function"!=typeof fetch?ia(b,d,e):fetch(b,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,d).then(e,function(h){F(`wasm streaming compile failed: ${h}`);F("falling back to ArrayBuffer instantiation");return ia(b,d,e)}))}function Aa(a,b,d){d=0<d?d:V(a)+1;d=Array(d);a=W(a,d,0,d.length);b&&(d.length=a);return d}function ja(){if(!(0<
G)){for(var a=Ba;0<a.length;)a.shift()(g);if(!(0<G||Q||(Q=!0,g.calledRun=!0,ea))){for(a=ka;0<a.length;)a.shift()(g);la(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();for(a=Ca;0<a.length;)a.shift()(g)}}}var g=aa,la,T;g.ready=new Promise((a,b)=>{la=a;T=b});var ma=Object.assign({},g),ha="object"==typeof window,P="function"==typeof importScripts,A="",U;if(ha||P)P?A=self.location.href:"undefined"!=typeof document&&document.currentScript&&(A=document.currentScript.src),A=import.meta.url,A=0!==
A.indexOf("blob:")?A.substr(0,A.replace(/[?#].*/,"").lastIndexOf("/")+1):"",P&&(U=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var Da=console.log.bind(console),F=console.error.bind(console);Object.assign(g,ma);ma=null;var O;"object"!=typeof WebAssembly&&E("no native wasm support detected");var M,ea=!1,y,x,S,r,v,ca,N,da,Ba=[],ka=[],Ca=[],G=0,X=null,H=null;if(g.locateFile){var B="ffmpeg.wasm";B.startsWith("data:application/octet-stream;base64,")||
(B=A+B)}else B=(new URL("ffmpeg.wasm",import.meta.url)).href;var na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b,d)=>{var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.buffer&&na)return na.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|
f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},V=a=>{for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++d):b+=3}return b},W=(a,b,d,e)=>{if(!(0<e))return 0;var f=d;e=d+e-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var n=a.charCodeAt(++h);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(d>=e)break;b[d++]=k}else{if(2047>=k){if(d+1>=e)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;b[d++]=224|k>>12}else{if(d+
3>=e)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f},pa=a=>{var b=V(a)+1,d=oa(b);d&&W(a,x,d,b);return d},Y={},J=()=>{if(!J.strings){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Y)void 0===Y[b]?delete a[b]:a[b]=Y[b];var d=[];for(b in a)d.push(`${b}=${a[b]}`);J.strings=d}return J.strings},
Ea=[null,[],[]],R=a=>0===a%4&&(0!==a%100||0===a%400),qa=[31,29,31,30,31,30,31,31,30,31,30,31],ra=[31,28,31,30,31,30,31,31,30,31,30,31],C=[],z,D,sa=[],va=(a,b,d,e,f)=>{f={string:m=>{var p=0;if(null!==m&&void 0!==m&&0!==m){p=V(m)+1;var K=Z(p);W(m,x,K,p);p=K}return p},array:m=>{var p=Z(m.length);y.set(m,p);return p}};a=g["_"+a];var h=[],k=0;if(e)for(var n=0;n<e.length;n++){var w=f[d[n]];w?(0===k&&(k=ta()),h[n]=w(e[n])):h[n]=e[n]}d=a.apply(null,h);return d=function(m){0!==k&&ua(k);m="string"===b?m?I(x,
m,void 0):"":"boolean"===b?!!m:m;return m}(d)},xa={__syscall_fcntl64:function(a,b,d){return 0},__syscall_openat:function(a,b,d,e){},_emscripten_get_now_is_monotonic:()=>!0,_gmtime_js:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);r[b>>2]=a.getUTCSeconds();r[b+4>>2]=a.getUTCMinutes();r[b+8>>2]=a.getUTCHours();r[b+12>>2]=a.getUTCDate();r[b+16>>2]=a.getUTCMonth();r[b+20>>2]=a.getUTCFullYear()-1900;r[b+24>>2]=a.getUTCDay();var d=Date.UTC(a.getUTCFullYear(),0,1,
0,0,0,0);a=(a.getTime()-d)/864E5|0;r[b+28>>2]=a},_tzset_js:(a,b,d)=>{function e(w){return(w=w.toTimeString().match(/\(([A-Za-z ]+)\)$/))?w[1]:"GMT"}var f=(new Date).getFullYear(),h=new Date(f,0,1),k=new Date(f,6,1);f=h.getTimezoneOffset();var n=k.getTimezoneOffset();v[a>>2]=60*Math.max(f,n);r[b>>2]=Number(f!=n);a=e(h);b=e(k);a=pa(a);b=pa(b);n<f?(v[d>>2]=a,v[d+4>>2]=b):(v[d>>2]=b,v[d+4>>2]=a)},abort:()=>{E("")},emscripten_date_now:()=>Date.now(),emscripten_get_now:()=>performance.now(),emscripten_memcpy_js:(a,
b,d)=>x.copyWithin(a,b,b+d),emscripten_resize_heap:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=(f.min.call(f,2147483648,e+(65536-e%65536)%65536)-M.buffer.byteLength+65535)/65536;try{M.grow(f);ba();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},environ_get:(a,b)=>{var d=0;J().forEach((e,f)=>{var h=b+d;f=v[a+4*f>>2]=h;for(h=0;h<e.length;++h)y[f++>>0]=e.charCodeAt(h);y[f>>0]=0;d+=e.length+
1});return 0},environ_sizes_get:(a,b)=>{var d=J();v[a>>2]=d.length;var e=0;d.forEach(f=>e+=f.length+1);v[b>>2]=e;return 0},fd_close:a=>52,fd_fdstat_get:(a,b)=>{var d=0;if(0==a)d=2;else if(1==a||2==a)d=64;y[b>>0]=2;S[b+2>>1]=1;N[b+8>>3]=BigInt(d);N[b+16>>3]=BigInt(0);return 0},fd_read:(a,b,d,e)=>52,fd_seek:function(a,b,d,e){return 70},fd_write:(a,b,d,e)=>{for(var f=0,h=0;h<d;h++){var k=v[b>>2],n=v[b+4>>2];b+=8;for(var w=0;w<n;w++){var m=x[k+w],p=Ea[a];0===m||10===m?((1===a?Da:F)(I(p,0)),p.length=0):
p.push(m)}f+=n}v[e>>2]=f;return 0},strftime:(a,b,d,e)=>{function f(c,l,t){for(c="number"==typeof c?c.toString():c||"";c.length<l;)c=t[0]+c;return c}function h(c,l){return f(c,l,"0")}function k(c,l){function t(L){return 0>L?-1:0<L?1:0}var u;0===(u=t(c.getFullYear()-l.getFullYear()))&&0===(u=t(c.getMonth()-l.getMonth()))&&(u=t(c.getDate()-l.getDate()));return u}function n(c){switch(c.getDay()){case 0:return new Date(c.getFullYear()-1,11,29);case 1:return c;case 2:return new Date(c.getFullYear(),0,3);
case 3:return new Date(c.getFullYear(),0,2);case 4:return new Date(c.getFullYear(),0,1);case 5:return new Date(c.getFullYear()-1,11,31);case 6:return new Date(c.getFullYear()-1,11,30)}}function w(c){a:{var l=c.tm_yday;for(c=new Date((new Date(c.tm_year+1900,0,1)).getTime());0<l;){var t=R(c.getFullYear()),u=c.getMonth();t=(t?qa:ra)[u];if(l>t-c.getDate())l-=t-c.getDate()+1,c.setDate(1),11>u?c.setMonth(u+1):(c.setMonth(0),c.setFullYear(c.getFullYear()+1));else{c.setDate(c.getDate()+l);l=c;break a}}l=
c}u=new Date(l.getFullYear(),0,4);c=new Date(l.getFullYear()+1,0,4);u=n(u);c=n(c);return 0>=k(u,l)?0>=k(c,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var m=v[e+40>>2];e={tm_sec:r[e>>2],tm_min:r[e+4>>2],tm_hour:r[e+8>>2],tm_mday:r[e+12>>2],tm_mon:r[e+16>>2],tm_year:r[e+20>>2],tm_wday:r[e+24>>2],tm_yday:r[e+28>>2],tm_isdst:r[e+32>>2],tm_gmtoff:r[e+36>>2],tm_zone:m?m?I(x,m,void 0):"":""};d=d?I(x,d,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p",
"%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)d=d.replace(new RegExp(p,"g"),m[p]);var K="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),wa="January February March April May June July August September October November December".split(" ");
m={"%a":c=>K[c.tm_wday].substring(0,3),"%A":c=>K[c.tm_wday],"%b":c=>wa[c.tm_mon].substring(0,3),"%B":c=>wa[c.tm_mon],"%C":c=>h((c.tm_year+1900)/100|0,2),"%d":c=>h(c.tm_mday,2),"%e":c=>f(c.tm_mday,2," "),"%g":c=>w(c).toString().substring(2),"%G":c=>w(c),"%H":c=>h(c.tm_hour,2),"%I":c=>{c=c.tm_hour;0==c?c=12:12<c&&(c-=12);return h(c,2)},"%j":c=>{for(var l=c.tm_mday,t=R(c.tm_year+1900)?qa:ra,u=0,L=0;L<=c.tm_mon-1;u+=t[L++]);return h(l+u,3)},"%m":c=>h(c.tm_mon+1,2),"%M":c=>h(c.tm_min,2),"%n":()=>"\n",
"%p":c=>0<=c.tm_hour&&12>c.tm_hour?"AM":"PM","%S":c=>h(c.tm_sec,2),"%t":()=>"\t","%u":c=>c.tm_wday||7,"%U":c=>h(Math.floor((c.tm_yday+7-c.tm_wday)/7),2),"%V":c=>{var l=Math.floor((c.tm_yday+7-(c.tm_wday+6)%7)/7);2>=(c.tm_wday+371-c.tm_yday-2)%7&&l++;if(l)53==l&&(t=(c.tm_wday+371-c.tm_yday)%7,4==t||3==t&&R(c.tm_year)||(l=1));else{l=52;var t=(c.tm_wday+7-c.tm_yday-1)%7;(4==t||5==t&&R(c.tm_year%400-1))&&l++}return h(l,2)},"%w":c=>c.tm_wday,"%W":c=>h(Math.floor((c.tm_yday+7-(c.tm_wday+6)%7)/7),2),"%y":c=>
(c.tm_year+1900).toString().substring(2),"%Y":c=>c.tm_year+1900,"%z":c=>{c=c.tm_gmtoff;var l=0<=c;c=Math.abs(c)/60;return(l?"+":"-")+String("0000"+(c/60*100+c%60)).slice(-4)},"%Z":c=>c.tm_zone,"%%":()=>"%"};d=d.replace(/%%/g,"\x00\x00");for(p in m)d.includes(p)&&(d=d.replace(new RegExp(p,"g"),m[p](e)));d=d.replace(/\0\0/g,"%");p=Aa(d,!1);if(p.length>b)return 0;y.set(p,a);return p.length-1}},q=function(){var a={env:xa,wasi_snapshot_preview1:xa};G++;za(O,B,a,function(b){q=b.instance.exports;M=q.memory;
ba();z=q.__indirect_function_table;ka.unshift(q.__wasm_call_ctors);G--;0==G&&(null!==X&&(clearInterval(X),X=null),H&&(b=H,H=null,b()))}).catch(T);return{}}();g._avio_alloc_context=(a,b,d,e,f,h,k)=>(g._avio_alloc_context=q.avio_alloc_context)(a,b,d,e,f,h,k);g._avformat_open_input=(a,b,d,e)=>(g._avformat_open_input=q.avformat_open_input)(a,b,d,e);g._avformat_find_stream_info=(a,b)=>(g._avformat_find_stream_info=q.avformat_find_stream_info)(a,b);g._avformat_alloc_context=()=>(g._avformat_alloc_context=
q.avformat_alloc_context)();g._av_malloc=a=>(g._av_malloc=q.av_malloc)(a);g._av_free=a=>(g._av_free=q.av_free)(a);g._av_get_bits_per_pixel=a=>(g._av_get_bits_per_pixel=q.av_get_bits_per_pixel)(a);g._av_pix_fmt_desc_next=a=>(g._av_pix_fmt_desc_next=q.av_pix_fmt_desc_next)(a);g._av_pix_fmt_desc_get_id=a=>(g._av_pix_fmt_desc_get_id=q.av_pix_fmt_desc_get_id)(a);g._av_version_info=()=>(g._av_version_info=q.av_version_info)();g._avutil_configuration=()=>(g._avutil_configuration=q.avutil_configuration)();
g._sws_isSupportedInput=a=>(g._sws_isSupportedInput=q.sws_isSupportedInput)(a);g._sws_isSupportedOutput=a=>(g._sws_isSupportedOutput=q.sws_isSupportedOutput)(a);var oa=g._malloc=a=>(oa=g._malloc=q.malloc)(a);g._free=a=>(g._free=q.free)(a);var ta=()=>(ta=q.stackSave)(),ua=a=>(ua=q.stackRestore)(a),Z=a=>(Z=q.stackAlloc)(a);g.getNativeTypeSize=function(a){switch(a){case "i1":case "i8":case "u8":return 1;case "i16":case "u16":return 2;case "i32":case "u32":return 4;case "i64":case "u64":return 8;case "float":return 4;
case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){const b=Number(a.substr(1));0!==b%8&&E("getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}};g.ccall=va;g.cwrap=(a,b,d,e)=>{var f=!d||d.every(h=>"number"===h||"boolean"===h);return"string"!==b&&f&&!e?g["_"+a]:function(){return va(a,b,d,arguments,e)}};g.addFunction=(a,b)=>{if(!D){D=new WeakMap;var d=z.length;if(D)for(var e=0;e<0+d;e++){var f=e;var h=C[f];h||(f>=C.length&&(C.length=f+1),C[f]=h=z.get(f));(f=
h)&&D.set(f,e)}}if(d=D.get(a)||0)return d;if(sa.length)d=sa.pop();else{try{z.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}d=z.length-1}try{e=d,z.set(e,a),C[e]=z.get(e)}catch(n){if(!(n instanceof TypeError))throw n;if("function"==typeof WebAssembly.Function){e=WebAssembly.Function;f={i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"};h={parameters:[],results:"v"==b[0]?[]:[f[b[0]]]};for(var k=1;k<b.length;++k)h.parameters.push(f[b[k]]);
b=new e(h,a)}else{e=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124,e:111};e.push(96);k=b.length;128>k?e.push(k):e.push(k%128|128,k>>7);for(k=0;k<b.length;++k)e.push(h[b[k]]);"v"==f?e.push(0):e.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];f=e.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push.apply(b,e);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}e=d;z.set(e,b);C[e]=z.get(e)}D.set(a,d);
return d};g.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return S[a>>1];case "i32":return r[a>>2];case "i64":return N[a>>3];case "float":return ca[a>>2];case "double":return da[a>>3];case "*":return v[a>>2];default:E(`invalid type for getValue: ${b}`)}};g.UTF8ToString=(a,b)=>a?I(x,a,b):"";g.writeArrayToMemory=(a,b)=>{y.set(a,b)};var Q;H=function b(){Q||ja();Q||(H=b)};ja();return aa.ready})();export default Module;
